### ISSUE TITLE
tito example GitHub repos for one to learn from?

### ISSUE THREAD

**Issue by fusion809** [rpm-software-management/tito#243]
Hi,

I am interested in possibly trying out this tool but I would like to see some (at least 5) example GitHub repos that are being used by Copr (with the help of tito to convert to SRPMs) to build RPMs. This would serve to help teach me how to do this myself. I learn best by seeing examples, rather than reading documentation. I would also like to ask is it possible to use tito to download the necessary sources (like tarballs of the upstream source that are listed in the spec file) to build the SRPM? So one does not have to manually upload the upstream source to Copr or GitHub, as tito running on the Copr build instances will download the necessary upstream sources for you. For example, to create a tito-suitable GitHub repo for clang would one have to upload the upstream source code tarball cfe-3.9.0.src.tar.xz to the GitHub repo or would tito automatically download it from the upstream URL listed in the clang.spec file?

Thanks for your time,
Brenton

**Comment by xsuchy** [comment]
> I am interested in possibly trying out this tool but I would like to see some (at least 5) example GitHub repos that are being used by Copr (with the help of tito to convert to SRPMs) to build RPMs.

https://github.com/rpm-software-management/mock
https://pagure.io/copr/copr
https://github.com/dgoodwin/tito
https://github.com/rpm-software-management/dnf
https://github.com/rpm-software-management/dnf-plugins-core

> I would also like to ask is it possible to use tito to download the necessary sources

Not possible with Tito.

**Comment by jmrodri** [comment]
More projects:

https://github.com/candlepin/candlepin
https://github.com/candlepin/python-rhsm
https://github.com/candlepin/subscription-manager
https://github.com/candlepin/rho
https://github.com/jmrodri/sm-photo-tool

There are probably others but that's a good set.

**Comment by FrostyX** [comment]
I've submitted a PR #375 with the list of projects that @xsuchy and @jmrodri posted above.
If I see correctly, the questions were answered, so once the PR gets merged, I will close this issue.

> I would also like to ask is it possible to use tito to download the necessary sources (like tarballs of the upstream source that are listed in the spec file) to build the SRPM?

Just to provide a bit more complete (or rather different) answer - Tito targets mainly on upstream developers that are distribution package managers at the same time. From the question, it seems like you are a package manager that doesn't have control over the upstream repository. I believe Tito (with a little bit of tweaking) can be used in such a manner but please be aware that it is a special case instead of intended main use-case.

If you are interested in using Tito in this way, please file a new issue and we can have a separate discussion over that topic.
