### ISSUE TITLE
manage __version__ numbers in __init__.py

### ISSUE THREAD

**Issue by ktdreyer** [rpm-software-management/tito#252]
https://www.python.org/dev/peps/pep-0396/ specifies how Python packages should define a `__version__ variable`.

If a package has a `__version__` variable defined in an `__init__.py`, Tito should increment that value (similar to the existing Tito method `_update_setup_py()`)

**Comment by ktdreyer** [comment]
@hluk showed me a great way to do this using tito's `[version_template]`.

```
$ cat .tito/templates/__init__.py.in
__version__ = '$version'

$ cat .tito/tito.props
...
[version_template]
destination_file = my_package/__init__.py
template_file = .tito/templates/__init__.py.in
```

**Comment by ktdreyer** [comment]
We can template `__init__.py` as a workaround, but that ties the package more into tito's way of operating and makes it a little more complex for new contributors to get up to speed.

It would be great to *automatically* bump the version number (like `_update_setup_py()`) without having to template a file.

**Comment by FrostyX** [comment]
Maybe there was a misunderstanding on my side, so I want to ask one thing to make it all clear. Are we talking about having a `__version__` number for the Tito project or are we talking about managing `__version__` number for projects managed by Tito?

**Comment by ktdreyer** [comment]
I think it's great that Tito has a `__version__` attribute (PR #371).

When I opened this ticket, I was requesting that Tito automatically discover and bump any package's `__version__` attribute, in the same way that Tito automatically bumps the version number in `setup.py`.

This would make it easier for new users to adopt Tito. It would make Tito operate in the same way that a human would operate when bumping their Python package manually.

**Comment by FrostyX** [comment]
Okay, I see. While it sounds intriguing, I am afraid, there are some things that would have to be considered.

- Not all projects would want this feature enabled, so we would need a toggle configuration
- Some project might have `setup.py` in _non-standard_ path, so we would need to have a configuration option for specifying it (or scan every directory)
- Some projects might have multiple `setup.py` files or another way of defining multiple packages. It would need to be addressed somehow.

Since this feature can be easily _workarounded_ with `[version_template]`, it is a very low priority for me. But everybody else, please feel free to hack on it.

@ktdreyer In the meantime, maybe we can at least improve our documentation to show how to use a template?

**Comment by ktdreyer** [comment]
@FrostyX `src/tito/tagger/main.py` currently calls `_update_setup_py()`. That feature is great. I think we would need to add a corresponding `_update_init_py()` method here.
